#server.address=192.168.137.1
#server.address=192.168.43.182
#server.address=127.0.0.1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/isboco_database
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
debug=true
spring.main.allow-circular-references=true
#spring.datasource.continue-on-error=true
spring.mvc.static-path-pattern=/uploads/**
spring.resources.static-locations=/app/uploads/
mailersend.api.key=mlsn.6b64022a122971e19edec87b726ad5cee4ff40fba77ff394635c40d31b377f37

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e8c35471e1c1bc
spring.mail.password=d6b84bbde2f988
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true