## This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
## For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
#
#name: Package FingerPrint
#
#on:
#  push:
#    branches: ["prod"]
#
#  workflow_dispatch:
##  release:
##    types: [created]
#
#jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres
#
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#          POSTGRES_DB: isboco_database
#
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
#
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#        settings-path: ${{ github.workspace }} # location for the settings.xml file
#
#    - uses: kolok/deploy-to-scalingo@v1
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#        app-name: is-fing
#        known-host: ssh.osc-fr1.scalingo.com